# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:47
from __future__ import unicode_literals

import core.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('language', models.CharField(default='ES', max_length=2)),
                ('picture', models.ImageField(upload_to=core.models.Channel.image_path)),
                ('parent_channel', models.ForeignKey(blank=True, null=True, on_delete=models.SET(core.models.get_default_channel), related_name='subchannels', to='core.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('metadata', jsonfield.fields.JSONField()),
                ('file', models.FileField(upload_to=core.models.Content.content_path)),
                ('channel', models.ForeignKey(default=core.models.get_default_channel, on_delete=models.SET(core.models.get_default_channel), to='core.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('average', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Content')),
            ],
        ),
    ]
