# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 13:48
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(default='channel_files/default.png', upload_to=core.models.Channel.image_path),
        ),
        migrations.AlterField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(on_delete=models.SET(core.models.get_default_channel), to='core.Channel'),
        ),
    ]
